package texto;

public class textoform extends javax.swing.JFrame {
    
    /** Creates new form textoform */
    public textoform() {
        initComponents();
        this.setTitle(title + "new document]");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //                           
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTO = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smNew = new javax.swing.JMenuItem();
        smOpen = new javax.swing.JMenuItem();
        smSave1 = new javax.swing.JMenuItem();
        smSave2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TEXTO.setColumns(20);
        TEXTO.setRows(5);
        TEXTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXTOKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TEXTO);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        smNew.setText("Nuevo");
        smNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smNewActionPerformed(evt);
            }
        });
        jMenu1.add(smNew);

        smOpen.setText("Abrir archivo...");
        smOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smOpenActionPerformed(evt);
            }
        });
        jMenu1.add(smOpen);

        smSave1.setText("Guardar");
        smSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSave1ActionPerformed(evt);
            }
        });
        jMenu1.add(smSave1);

        smSave2.setText("Guardar como");
        smSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSave2ActionPerformed(evt);
            }
        });
        jMenu1.add(smSave2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        smAcerca.setText("Acerca de...");
        smAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smAcercaActionPerformed(evt);
            }
        });
        jMenu2.add(smAcerca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }//                         

    private void smOpenActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // Abre archivo de texto            
       isnew=tc.Dialog("Open",TEXTO);   
       this.setTitle(title + tc.ruta+"]");
    }                                      

    private void smSave2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // Guarda en un nuevo archivo
       isnew=tc.Dialog("Save As",  TEXTO); 
        this.setTitle(title + tc.ruta+"]");
}                                       

    private void smSave1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // Guarda modificaciones de un archivo abierto
        if (isnew) {
           isnew = tc.Dialog("Save As", TEXTO);
           this.setTitle(title + tc.ruta + "]");
        }
        else
        {                 
            isnew=tc.Dialog("Save", TEXTO);   
            this.setTitle(title + tc.ruta+"]");
        }
    }                                       

    private void TEXTOKeyReleased(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
        
    }                                 

    private void smNewActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        TEXTO.setText("");
        isnew=true;
        this.setTitle(title + "new document]");
    }                                     

    private void smAcercaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        TEXTO.setText("visitame: javayotros.blogspot.com");
    }                                        
    
    /**
     * @param args the command line arguments
     */
    textoclass tc = new textoclass();
    Boolean isnew = true;
    String title = "Editor de Texto :[";
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new textoform().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JTextArea TEXTO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem smAcerca;
    private javax.swing.JMenuItem smNew;
    private javax.swing.JMenuItem smOpen;
    private javax.swing.JMenuItem smSave1;
    private javax.swing.JMenuItem smSave2;
    // End of variables declaration                   
    
}